theme: 
  - noesya-hugo-theme
  - osuny-plugin-centered-layout
  - osuny-plugin-single-page-application
_merge: deep
params:
  additional_csp: 'unpkg.com'
  home:
    head:
      title: site
  image_sizes:
    sections:
      pages:
        hero:
          mobile: 400
          tablet: 800
          desktop: 300
        item:
          mobile: 420
          tablet: 800
          desktop: 420